### ISSUE TITLE
hulk

### ISSUE THREAD

**Issue by MaharajanR** [gingeleski/helloworld-cucumber-java-gradle#2]
![146393](https://github.com/gingeleski/helloworld-cucumber-java-gradle/assets/12625484/059a436e-3cc4-444d-a3fb-9c43c4d4a47b)

**Comment by gingeleski** [comment]
I am a Warner Bros. Discovery employee, we own DC, please [**DC only**](https://www.cbr.com/wildcats-seven-warriors-maul-hulk-copy-dc/)

Closing this issue, thanks 😉
